[[main]]
name = "About"
pageRef = "about"
weight = 10

[[main]]
name = "Posts"
pageRef = "posts"
weight = 20

[[main]]
name = "Updates"
pageRef = "updates"
weight = 30

[[main]]
name = "Scripts"
pageRef = "scripts"
weight = 40

[[main]]
name = "My Gear"
pageRef = "gear"
weight = 50

[[main]]
name = "Merch"
url = "https://shop.xerolinux.xyz/"
weight = 60

[[main]]
name = "Wiki"
url = "https://wiki.xerolinux.xyz/"
weight = 70

[[main]]
pre = "rss"
url = "/index.xml"
weight = 80

[[footer]]
none = "none"
