# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

replyByEmail = false

mainSections = [ "posts", "updates" ]
# robots = ""

disableImageZoom = true
disableImageOptimization = true
disableTextInHeader = false
# backgroundImageWidth = 1200

defaultBackgroundImage = "img/bg.webp"
defaultFeaturedImage = "img/defaultf.png"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed-fill-blur" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "page" # valid options: page, profile, hero, card, background, custom
  background = "img/bg.webp" # used in: hero, and card
  showRecent = false
  showRecentItems = 12
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = true
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = true
  showViews = true
  showLikes = true
  showDateOnlyInArticle = false
  showDateUpdated = true
  showAuthor = true
  showAuthorBottom = false
  showHero = false
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = false
  # editURL = "https://github.com/xerolinux/xerohub/"
  # editAppendPath = false
  seriesOpened = false
  showHeadingAnchors = false
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showAuthorsBadges = true
  showWordCount = false
  sharingLinks = [ "linkedin", "twitter", "bluesky", "mastodon", "reddit", "facebook", "whatsapp", "telegram"]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = false # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = false
  orderByWeight = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = true
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = true

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = true

[firebase]
  apiKey = "AIzaSyDT_MJQFqPiRXwqJzRJN_VdNR9qF-1ki_s"
  authDomain = "xerolinux-6e564.firebaseapp.com"
  projectId = "xerolinux-6e564"
  storageBucket = "xerolinux-6e564.appspot.com"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  measurementId = "G-XTMB3XQHP4"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  # websiteid = "ABC12345"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # scriptName = ""
  # enableTrackEvent = true

[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = true

[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
  # fediverse = ""

[rssnext]
  # feedId = ""
  # userId = ""
